<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VariableSeeder extends Seeder
{
    public function run(): void
    {
        $variables = array(
            array(
                'id' => '1', 'questionnaire_id' => '1', 'name' => 'Controllo Emotivo', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44', 'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '2', 'questionnaire_id' => '1', 'name' => 'Controllo della Minaccia', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44', 'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '3', 'questionnaire_id' => '1', 'name' => 'Controllo dei livelli di stress',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44',
                'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '4', 'questionnaire_id' => '2', 'name' => 'Totale', 'gender_based' => '0', 'deleted_at' => null,
                'created_at' => '2024-06-10 21:33:44', 'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '5', 'questionnaire_id' => '3', 'name' => 'Fiducia', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44', 'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '6', 'questionnaire_id' => '3', 'name' => 'Disagio nelle relazioni intime',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44',
                'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '7', 'questionnaire_id' => '3', 'name' => 'Relazioni considerate come secondarie',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44',
                'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '8', 'questionnaire_id' => '3', 'name' => 'Preoccupazioni riguardo alle relazioni intime',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44',
                'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '9', 'questionnaire_id' => '3', 'name' => 'Bisogno di approvazione', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:44', 'updated_at' => '2024-06-10 21:33:44'
            ),
            array(
                'id' => '11', 'questionnaire_id' => '5', 'name' => 'Punteggio Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:45', 'updated_at' => '2024-06-10 21:33:45'
            ),
            array(
                'id' => '12', 'questionnaire_id' => '6', 'name' => 'Tendenza a dimagrire', 'gender_based' => '1',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:45', 'updated_at' => '2024-06-10 21:33:45'
            ),
            array(
                'id' => '13', 'questionnaire_id' => '6', 'name' => 'Bulimia', 'gender_based' => '1',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:45', 'updated_at' => '2024-06-10 21:33:45'
            ),
            array(
                'id' => '14', 'questionnaire_id' => '6', 'name' => 'Insoddisfazione corporea', 'gender_based' => '1',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:45', 'updated_at' => '2024-06-10 21:33:45'
            ),
            array(
                'id' => '15', 'questionnaire_id' => '7', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:45', 'updated_at' => '2024-06-10 21:33:45'
            ),
            array(
                'id' => '16', 'questionnaire_id' => '8', 'name' => 'Critiche rivolte a sé stesso',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:45',
                'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '17', 'questionnaire_id' => '8',
                'name' => 'Critiche rivolte a sé stesso in relazione agli altri', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '18', 'questionnaire_id' => '9', 'name' => 'Obiettivi personali', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '19', 'questionnaire_id' => '9', 'name' => 'Timore degli errori', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '20', 'questionnaire_id' => '9', 'name' => 'Critiche genitoriali', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '21', 'questionnaire_id' => '9', 'name' => 'Aspettative genitoriali', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '22', 'questionnaire_id' => '9', 'name' => 'Dubbi sulle azioni', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '23', 'questionnaire_id' => '9', 'name' => 'Organizzazione', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '24', 'questionnaire_id' => '10', 'name' => 'Vantaggi del pensiero rimuginativo',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46',
                'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '25', 'questionnaire_id' => '10',
                'name' => 'Minaccia e incontrollabilità del pensiero rimuginativo', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '26', 'questionnaire_id' => '10', 'name' => 'Capacità di gestione dei pensieri',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46',
                'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '27', 'questionnaire_id' => '10', 'name' => 'Controllo dei pensieri', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '28', 'questionnaire_id' => '10', 'name' => 'Monitoraggio dei pensieri', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:46'
            ),
            array(
                'id' => '29', 'questionnaire_id' => '10', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:46', 'updated_at' => '2024-06-10 21:33:47'
            ),
            array(
                'id' => '30', 'questionnaire_id' => '11', 'name' => 'Funzionamento psicosociale globale',
                'gender_based' => '0', 'deleted_at' => null, 'created_at' => '2024-06-10 21:33:47',
                'updated_at' => '2024-06-10 21:33:47'
            ),
            array(
                'id' => '31', 'questionnaire_id' => '11', 'name' => 'Sintomi', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:47', 'updated_at' => '2024-06-10 21:33:47'
            ),
            array(
                'id' => '32', 'questionnaire_id' => '11', 'name' => 'Relazioni interpersonali', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:47', 'updated_at' => '2024-06-10 21:33:47'
            ),
            array(
                'id' => '33', 'questionnaire_id' => '11', 'name' => 'Ruolo sociale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:47', 'updated_at' => '2024-06-10 21:33:48'
            ),
            array(
                'id' => '34', 'questionnaire_id' => '12', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:48', 'updated_at' => '2024-06-10 21:33:48'
            ),
            array(
                'id' => '35', 'questionnaire_id' => '13', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:48', 'updated_at' => '2024-06-10 21:33:48'
            ),
            array(
                'id' => '36', 'questionnaire_id' => '14', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:48', 'updated_at' => '2024-06-10 21:33:48'
            ),
            array(
                'id' => '37', 'questionnaire_id' => '15', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:48', 'updated_at' => '2024-06-10 21:33:48'
            ),
            array(
                'id' => '38', 'questionnaire_id' => '16', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:48', 'updated_at' => '2024-06-10 21:33:49'
            ),
            array(
                'id' => '39', 'questionnaire_id' => '17', 'name' => 'Punteggio Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:49', 'updated_at' => '2024-06-10 21:33:49'
            ),
            array(
                'id' => '40', 'questionnaire_id' => '23', 'name' => 'Totale', 'gender_based' => '0',
                'deleted_at' => null, 'created_at' => '2024-06-10 21:33:49', 'updated_at' => '2024-06-10 21:33:49'
            )
        );

        $question_variable = array(
            array('id' => '1', 'question_id' => '5', 'variable_id' => '1'),
            array('id' => '2', 'question_id' => '6', 'variable_id' => '1'),
            array('id' => '3', 'question_id' => '10', 'variable_id' => '1'),
            array('id' => '4', 'question_id' => '13', 'variable_id' => '1'),
            array('id' => '5', 'question_id' => '15', 'variable_id' => '1'),
            array('id' => '6', 'question_id' => '3', 'variable_id' => '2'),
            array('id' => '7', 'question_id' => '4', 'variable_id' => '2'),
            array('id' => '8', 'question_id' => '7', 'variable_id' => '2'),
            array('id' => '9', 'question_id' => '8', 'variable_id' => '2'),
            array('id' => '10', 'question_id' => '9', 'variable_id' => '2'),
            array('id' => '11', 'question_id' => '12', 'variable_id' => '2'),
            array('id' => '12', 'question_id' => '1', 'variable_id' => '3'),
            array('id' => '13', 'question_id' => '2', 'variable_id' => '3'),
            array('id' => '14', 'question_id' => '11', 'variable_id' => '3'),
            array('id' => '15', 'question_id' => '14', 'variable_id' => '3'),
            array('id' => '16', 'question_id' => '16', 'variable_id' => '4'),
            array('id' => '17', 'question_id' => '17', 'variable_id' => '4'),
            array('id' => '18', 'question_id' => '18', 'variable_id' => '4'),
            array('id' => '19', 'question_id' => '19', 'variable_id' => '4'),
            array('id' => '20', 'question_id' => '20', 'variable_id' => '4'),
            array('id' => '21', 'question_id' => '21', 'variable_id' => '4'),
            array('id' => '22', 'question_id' => '22', 'variable_id' => '4'),
            array('id' => '23', 'question_id' => '23', 'variable_id' => '4'),
            array('id' => '24', 'question_id' => '24', 'variable_id' => '4'),
            array('id' => '25', 'question_id' => '25', 'variable_id' => '4'),
            array('id' => '26', 'question_id' => '26', 'variable_id' => '4'),
            array('id' => '27', 'question_id' => '27', 'variable_id' => '4'),
            array('id' => '28', 'question_id' => '28', 'variable_id' => '4'),
            array('id' => '29', 'question_id' => '29', 'variable_id' => '5'),
            array('id' => '30', 'question_id' => '30', 'variable_id' => '5'),
            array('id' => '31', 'question_id' => '31', 'variable_id' => '5'),
            array('id' => '32', 'question_id' => '47', 'variable_id' => '5'),
            array('id' => '33', 'question_id' => '59', 'variable_id' => '5'),
            array('id' => '34', 'question_id' => '61', 'variable_id' => '5'),
            array('id' => '35', 'question_id' => '65', 'variable_id' => '5'),
            array('id' => '36', 'question_id' => '66', 'variable_id' => '5'),
            array('id' => '37', 'question_id' => '32', 'variable_id' => '6'),
            array('id' => '38', 'question_id' => '33', 'variable_id' => '6'),
            array('id' => '39', 'question_id' => '44', 'variable_id' => '6'),
            array('id' => '40', 'question_id' => '45', 'variable_id' => '6'),
            array('id' => '41', 'question_id' => '48', 'variable_id' => '6'),
            array('id' => '42', 'question_id' => '49', 'variable_id' => '6'),
            array('id' => '43', 'question_id' => '51', 'variable_id' => '6'),
            array('id' => '44', 'question_id' => '53', 'variable_id' => '6'),
            array('id' => '45', 'question_id' => '54', 'variable_id' => '6'),
            array('id' => '46', 'question_id' => '62', 'variable_id' => '6'),
            array('id' => '47', 'question_id' => '34', 'variable_id' => '7'),
            array('id' => '48', 'question_id' => '35', 'variable_id' => '7'),
            array('id' => '49', 'question_id' => '36', 'variable_id' => '7'),
            array('id' => '50', 'question_id' => '37', 'variable_id' => '7'),
            array('id' => '51', 'question_id' => '38', 'variable_id' => '7'),
            array('id' => '52', 'question_id' => '42', 'variable_id' => '7'),
            array('id' => '53', 'question_id' => '64', 'variable_id' => '7'),
            array('id' => '54', 'question_id' => '46', 'variable_id' => '8'),
            array('id' => '55', 'question_id' => '50', 'variable_id' => '8'),
            array('id' => '56', 'question_id' => '56', 'variable_id' => '8'),
            array('id' => '57', 'question_id' => '57', 'variable_id' => '8'),
            array('id' => '58', 'question_id' => '58', 'variable_id' => '8'),
            array('id' => '59', 'question_id' => '60', 'variable_id' => '8'),
            array('id' => '60', 'question_id' => '67', 'variable_id' => '8'),
            array('id' => '61', 'question_id' => '68', 'variable_id' => '8'),
            array('id' => '62', 'question_id' => '39', 'variable_id' => '9'),
            array('id' => '63', 'question_id' => '40', 'variable_id' => '9'),
            array('id' => '64', 'question_id' => '41', 'variable_id' => '9'),
            array('id' => '65', 'question_id' => '43', 'variable_id' => '9'),
            array('id' => '66', 'question_id' => '52', 'variable_id' => '9'),
            array('id' => '67', 'question_id' => '55', 'variable_id' => '9'),
            array('id' => '68', 'question_id' => '63', 'variable_id' => '9'),
            array('id' => '89', 'question_id' => '89', 'variable_id' => '11'),
            array('id' => '90', 'question_id' => '90', 'variable_id' => '11'),
            array('id' => '91', 'question_id' => '91', 'variable_id' => '11'),
            array('id' => '92', 'question_id' => '92', 'variable_id' => '11'),
            array('id' => '93', 'question_id' => '93', 'variable_id' => '11'),
            array('id' => '94', 'question_id' => '94', 'variable_id' => '11'),
            array('id' => '95', 'question_id' => '95', 'variable_id' => '11'),
            array('id' => '96', 'question_id' => '96', 'variable_id' => '11'),
            array('id' => '97', 'question_id' => '97', 'variable_id' => '11'),
            array('id' => '98', 'question_id' => '98', 'variable_id' => '11'),
            array('id' => '99', 'question_id' => '99', 'variable_id' => '11'),
            array('id' => '100', 'question_id' => '100', 'variable_id' => '11'),
            array('id' => '101', 'question_id' => '101', 'variable_id' => '11'),
            array('id' => '102', 'question_id' => '102', 'variable_id' => '11'),
            array('id' => '103', 'question_id' => '103', 'variable_id' => '11'),
            array('id' => '104', 'question_id' => '104', 'variable_id' => '11'),
            array('id' => '105', 'question_id' => '105', 'variable_id' => '11'),
            array('id' => '106', 'question_id' => '106', 'variable_id' => '11'),
            array('id' => '107', 'question_id' => '107', 'variable_id' => '11'),
            array('id' => '108', 'question_id' => '108', 'variable_id' => '11'),
            array('id' => '109', 'question_id' => '109', 'variable_id' => '11'),
            array('id' => '110', 'question_id' => '110', 'variable_id' => '11'),
            array('id' => '111', 'question_id' => '111', 'variable_id' => '11'),
            array('id' => '112', 'question_id' => '112', 'variable_id' => '11'),
            array('id' => '113', 'question_id' => '113', 'variable_id' => '11'),
            array('id' => '114', 'question_id' => '114', 'variable_id' => '11'),
            array('id' => '115', 'question_id' => '115', 'variable_id' => '11'),
            array('id' => '116', 'question_id' => '116', 'variable_id' => '11'),
            array('id' => '117', 'question_id' => '117', 'variable_id' => '11'),
            array('id' => '118', 'question_id' => '118', 'variable_id' => '11'),
            array('id' => '119', 'question_id' => '119', 'variable_id' => '11'),
            array('id' => '120', 'question_id' => '120', 'variable_id' => '11'),
            array('id' => '121', 'question_id' => '121', 'variable_id' => '11'),
            array('id' => '122', 'question_id' => '122', 'variable_id' => '11'),
            array('id' => '123', 'question_id' => '123', 'variable_id' => '11'),
            array('id' => '124', 'question_id' => '124', 'variable_id' => '11'),
            array('id' => '125', 'question_id' => '125', 'variable_id' => '12'),
            array('id' => '126', 'question_id' => '129', 'variable_id' => '12'),
            array('id' => '127', 'question_id' => '131', 'variable_id' => '12'),
            array('id' => '128', 'question_id' => '133', 'variable_id' => '12'),
            array('id' => '129', 'question_id' => '135', 'variable_id' => '12'),
            array('id' => '130', 'question_id' => '138', 'variable_id' => '12'),
            array('id' => '131', 'question_id' => '142', 'variable_id' => '12'),
            array('id' => '132', 'question_id' => '127', 'variable_id' => '13'),
            array('id' => '133', 'question_id' => '128', 'variable_id' => '13'),
            array('id' => '134', 'question_id' => '136', 'variable_id' => '13'),
            array('id' => '135', 'question_id' => '139', 'variable_id' => '13'),
            array('id' => '136', 'question_id' => '141', 'variable_id' => '13'),
            array('id' => '137', 'question_id' => '143', 'variable_id' => '13'),
            array('id' => '138', 'question_id' => '146', 'variable_id' => '13'),
            array('id' => '139', 'question_id' => '126', 'variable_id' => '14'),
            array('id' => '140', 'question_id' => '130', 'variable_id' => '14'),
            array('id' => '141', 'question_id' => '132', 'variable_id' => '14'),
            array('id' => '142', 'question_id' => '134', 'variable_id' => '14'),
            array('id' => '143', 'question_id' => '137', 'variable_id' => '14'),
            array('id' => '144', 'question_id' => '140', 'variable_id' => '14'),
            array('id' => '145', 'question_id' => '144', 'variable_id' => '14'),
            array('id' => '146', 'question_id' => '145', 'variable_id' => '14'),
            array('id' => '147', 'question_id' => '147', 'variable_id' => '14'),
            array('id' => '148', 'question_id' => '148', 'variable_id' => '15'),
            array('id' => '149', 'question_id' => '149', 'variable_id' => '15'),
            array('id' => '150', 'question_id' => '150', 'variable_id' => '15'),
            array('id' => '151', 'question_id' => '151', 'variable_id' => '15'),
            array('id' => '152', 'question_id' => '152', 'variable_id' => '15'),
            array('id' => '153', 'question_id' => '153', 'variable_id' => '15'),
            array('id' => '154', 'question_id' => '154', 'variable_id' => '15'),
            array('id' => '155', 'question_id' => '155', 'variable_id' => '15'),
            array('id' => '156', 'question_id' => '156', 'variable_id' => '15'),
            array('id' => '157', 'question_id' => '157', 'variable_id' => '15'),
            array('id' => '158', 'question_id' => '158', 'variable_id' => '15'),
            array('id' => '159', 'question_id' => '159', 'variable_id' => '15'),
            array('id' => '160', 'question_id' => '160', 'variable_id' => '15'),
            array('id' => '161', 'question_id' => '161', 'variable_id' => '15'),
            array('id' => '162', 'question_id' => '162', 'variable_id' => '15'),
            array('id' => '163', 'question_id' => '163', 'variable_id' => '15'),
            array('id' => '164', 'question_id' => '164', 'variable_id' => '15'),
            array('id' => '165', 'question_id' => '165', 'variable_id' => '15'),
            array('id' => '166', 'question_id' => '166', 'variable_id' => '15'),
            array('id' => '167', 'question_id' => '167', 'variable_id' => '15'),
            array('id' => '168', 'question_id' => '168', 'variable_id' => '15'),
            array('id' => '169', 'question_id' => '169', 'variable_id' => '15'),
            array('id' => '170', 'question_id' => '170', 'variable_id' => '15'),
            array('id' => '171', 'question_id' => '171', 'variable_id' => '15'),
            array('id' => '172', 'question_id' => '172', 'variable_id' => '15'),
            array('id' => '173', 'question_id' => '173', 'variable_id' => '15'),
            array('id' => '174', 'question_id' => '174', 'variable_id' => '15'),
            array('id' => '175', 'question_id' => '176', 'variable_id' => '16'),
            array('id' => '176', 'question_id' => '178', 'variable_id' => '16'),
            array('id' => '177', 'question_id' => '180', 'variable_id' => '16'),
            array('id' => '178', 'question_id' => '182', 'variable_id' => '16'),
            array('id' => '179', 'question_id' => '184', 'variable_id' => '16'),
            array('id' => '180', 'question_id' => '186', 'variable_id' => '16'),
            array('id' => '181', 'question_id' => '187', 'variable_id' => '16'),
            array('id' => '182', 'question_id' => '188', 'variable_id' => '16'),
            array('id' => '183', 'question_id' => '190', 'variable_id' => '16'),
            array('id' => '184', 'question_id' => '191', 'variable_id' => '16'),
            array('id' => '185', 'question_id' => '192', 'variable_id' => '16'),
            array('id' => '186', 'question_id' => '194', 'variable_id' => '16'),
            array('id' => '187', 'question_id' => '195', 'variable_id' => '16'),
            array('id' => '188', 'question_id' => '196', 'variable_id' => '16'),
            array('id' => '189', 'question_id' => '175', 'variable_id' => '17'),
            array('id' => '190', 'question_id' => '177', 'variable_id' => '17'),
            array('id' => '191', 'question_id' => '179', 'variable_id' => '17'),
            array('id' => '192', 'question_id' => '181', 'variable_id' => '17'),
            array('id' => '193', 'question_id' => '189', 'variable_id' => '17'),
            array('id' => '194', 'question_id' => '183', 'variable_id' => '17'),
            array('id' => '195', 'question_id' => '185', 'variable_id' => '17'),
            array('id' => '196', 'question_id' => '193', 'variable_id' => '17'),
            array('id' => '197', 'question_id' => '200', 'variable_id' => '18'),
            array('id' => '198', 'question_id' => '202', 'variable_id' => '18'),
            array('id' => '199', 'question_id' => '208', 'variable_id' => '18'),
            array('id' => '200', 'question_id' => '212', 'variable_id' => '18'),
            array('id' => '201', 'question_id' => '215', 'variable_id' => '18'),
            array('id' => '202', 'question_id' => '220', 'variable_id' => '18'),
            array('id' => '203', 'question_id' => '226', 'variable_id' => '18'),
            array('id' => '204', 'question_id' => '205', 'variable_id' => '19'),
            array('id' => '205', 'question_id' => '206', 'variable_id' => '19'),
            array('id' => '206', 'question_id' => '209', 'variable_id' => '19'),
            array('id' => '207', 'question_id' => '210', 'variable_id' => '19'),
            array('id' => '208', 'question_id' => '214', 'variable_id' => '19'),
            array('id' => '209', 'question_id' => '217', 'variable_id' => '19'),
            array('id' => '210', 'question_id' => '219', 'variable_id' => '19'),
            array('id' => '211', 'question_id' => '221', 'variable_id' => '19'),
            array('id' => '212', 'question_id' => '230', 'variable_id' => '19'),
            array('id' => '213', 'question_id' => '199', 'variable_id' => '20'),
            array('id' => '214', 'question_id' => '201', 'variable_id' => '20'),
            array('id' => '215', 'question_id' => '218', 'variable_id' => '20'),
            array('id' => '216', 'question_id' => '231', 'variable_id' => '20'),
            array('id' => '217', 'question_id' => '197', 'variable_id' => '21'),
            array('id' => '218', 'question_id' => '207', 'variable_id' => '21'),
            array('id' => '219', 'question_id' => '211', 'variable_id' => '21'),
            array('id' => '220', 'question_id' => '216', 'variable_id' => '21'),
            array('id' => '221', 'question_id' => '222', 'variable_id' => '21'),
            array('id' => '222', 'question_id' => '213', 'variable_id' => '22'),
            array('id' => '223', 'question_id' => '224', 'variable_id' => '22'),
            array('id' => '224', 'question_id' => '228', 'variable_id' => '22'),
            array('id' => '225', 'question_id' => '229', 'variable_id' => '22'),
            array('id' => '226', 'question_id' => '198', 'variable_id' => '23'),
            array('id' => '227', 'question_id' => '203', 'variable_id' => '23'),
            array('id' => '228', 'question_id' => '204', 'variable_id' => '23'),
            array('id' => '229', 'question_id' => '223', 'variable_id' => '23'),
            array('id' => '230', 'question_id' => '225', 'variable_id' => '23'),
            array('id' => '231', 'question_id' => '227', 'variable_id' => '23'),
            array('id' => '232', 'question_id' => '232', 'variable_id' => '24'),
            array('id' => '233', 'question_id' => '238', 'variable_id' => '24'),
            array('id' => '234', 'question_id' => '241', 'variable_id' => '24'),
            array('id' => '235', 'question_id' => '250', 'variable_id' => '24'),
            array('id' => '236', 'question_id' => '254', 'variable_id' => '24'),
            array('id' => '237', 'question_id' => '259', 'variable_id' => '24'),
            array('id' => '238', 'question_id' => '233', 'variable_id' => '25'),
            array('id' => '239', 'question_id' => '235', 'variable_id' => '25'),
            array('id' => '240', 'question_id' => '240', 'variable_id' => '25'),
            array('id' => '241', 'question_id' => '242', 'variable_id' => '25'),
            array('id' => '242', 'question_id' => '246', 'variable_id' => '25'),
            array('id' => '243', 'question_id' => '252', 'variable_id' => '25'),
            array('id' => '244', 'question_id' => '239', 'variable_id' => '26'),
            array('id' => '245', 'question_id' => '245', 'variable_id' => '26'),
            array('id' => '246', 'question_id' => '248', 'variable_id' => '26'),
            array('id' => '247', 'question_id' => '255', 'variable_id' => '26'),
            array('id' => '248', 'question_id' => '257', 'variable_id' => '26'),
            array('id' => '249', 'question_id' => '260', 'variable_id' => '26'),
            array('id' => '250', 'question_id' => '237', 'variable_id' => '27'),
            array('id' => '251', 'question_id' => '244', 'variable_id' => '27'),
            array('id' => '252', 'question_id' => '251', 'variable_id' => '27'),
            array('id' => '253', 'question_id' => '253', 'variable_id' => '27'),
            array('id' => '254', 'question_id' => '256', 'variable_id' => '27'),
            array('id' => '255', 'question_id' => '258', 'variable_id' => '27'),
            array('id' => '256', 'question_id' => '234', 'variable_id' => '28'),
            array('id' => '257', 'question_id' => '236', 'variable_id' => '28'),
            array('id' => '258', 'question_id' => '243', 'variable_id' => '28'),
            array('id' => '259', 'question_id' => '247', 'variable_id' => '28'),
            array('id' => '260', 'question_id' => '249', 'variable_id' => '28'),
            array('id' => '261', 'question_id' => '261', 'variable_id' => '28'),
            array('id' => '262', 'question_id' => '232', 'variable_id' => '29'),
            array('id' => '263', 'question_id' => '233', 'variable_id' => '29'),
            array('id' => '264', 'question_id' => '234', 'variable_id' => '29'),
            array('id' => '265', 'question_id' => '235', 'variable_id' => '29'),
            array('id' => '266', 'question_id' => '236', 'variable_id' => '29'),
            array('id' => '267', 'question_id' => '237', 'variable_id' => '29'),
            array('id' => '268', 'question_id' => '238', 'variable_id' => '29'),
            array('id' => '269', 'question_id' => '239', 'variable_id' => '29'),
            array('id' => '270', 'question_id' => '240', 'variable_id' => '29'),
            array('id' => '271', 'question_id' => '241', 'variable_id' => '29'),
            array('id' => '272', 'question_id' => '242', 'variable_id' => '29'),
            array('id' => '273', 'question_id' => '243', 'variable_id' => '29'),
            array('id' => '274', 'question_id' => '244', 'variable_id' => '29'),
            array('id' => '275', 'question_id' => '245', 'variable_id' => '29'),
            array('id' => '276', 'question_id' => '246', 'variable_id' => '29'),
            array('id' => '277', 'question_id' => '247', 'variable_id' => '29'),
            array('id' => '278', 'question_id' => '248', 'variable_id' => '29'),
            array('id' => '279', 'question_id' => '249', 'variable_id' => '29'),
            array('id' => '280', 'question_id' => '250', 'variable_id' => '29'),
            array('id' => '281', 'question_id' => '251', 'variable_id' => '29'),
            array('id' => '282', 'question_id' => '252', 'variable_id' => '29'),
            array('id' => '283', 'question_id' => '253', 'variable_id' => '29'),
            array('id' => '284', 'question_id' => '254', 'variable_id' => '29'),
            array('id' => '285', 'question_id' => '255', 'variable_id' => '29'),
            array('id' => '286', 'question_id' => '256', 'variable_id' => '29'),
            array('id' => '287', 'question_id' => '257', 'variable_id' => '29'),
            array('id' => '288', 'question_id' => '258', 'variable_id' => '29'),
            array('id' => '289', 'question_id' => '259', 'variable_id' => '29'),
            array('id' => '290', 'question_id' => '260', 'variable_id' => '29'),
            array('id' => '291', 'question_id' => '261', 'variable_id' => '29'),
            array('id' => '292', 'question_id' => '262', 'variable_id' => '30'),
            array('id' => '293', 'question_id' => '263', 'variable_id' => '30'),
            array('id' => '294', 'question_id' => '264', 'variable_id' => '30'),
            array('id' => '295', 'question_id' => '265', 'variable_id' => '30'),
            array('id' => '296', 'question_id' => '266', 'variable_id' => '30'),
            array('id' => '297', 'question_id' => '267', 'variable_id' => '30'),
            array('id' => '298', 'question_id' => '268', 'variable_id' => '30'),
            array('id' => '299', 'question_id' => '269', 'variable_id' => '30'),
            array('id' => '300', 'question_id' => '270', 'variable_id' => '30'),
            array('id' => '301', 'question_id' => '271', 'variable_id' => '30'),
            array('id' => '302', 'question_id' => '272', 'variable_id' => '30'),
            array('id' => '303', 'question_id' => '273', 'variable_id' => '30'),
            array('id' => '304', 'question_id' => '274', 'variable_id' => '30'),
            array('id' => '305', 'question_id' => '275', 'variable_id' => '30'),
            array('id' => '306', 'question_id' => '276', 'variable_id' => '30'),
            array('id' => '307', 'question_id' => '277', 'variable_id' => '30'),
            array('id' => '308', 'question_id' => '278', 'variable_id' => '30'),
            array('id' => '309', 'question_id' => '279', 'variable_id' => '30'),
            array('id' => '310', 'question_id' => '280', 'variable_id' => '30'),
            array('id' => '311', 'question_id' => '281', 'variable_id' => '30'),
            array('id' => '312', 'question_id' => '282', 'variable_id' => '30'),
            array('id' => '313', 'question_id' => '283', 'variable_id' => '30'),
            array('id' => '314', 'question_id' => '284', 'variable_id' => '30'),
            array('id' => '315', 'question_id' => '285', 'variable_id' => '30'),
            array('id' => '316', 'question_id' => '286', 'variable_id' => '30'),
            array('id' => '317', 'question_id' => '287', 'variable_id' => '30'),
            array('id' => '318', 'question_id' => '288', 'variable_id' => '30'),
            array('id' => '319', 'question_id' => '289', 'variable_id' => '30'),
            array('id' => '320', 'question_id' => '290', 'variable_id' => '30'),
            array('id' => '321', 'question_id' => '291', 'variable_id' => '30'),
            array('id' => '322', 'question_id' => '292', 'variable_id' => '30'),
            array('id' => '323', 'question_id' => '293', 'variable_id' => '30'),
            array('id' => '324', 'question_id' => '294', 'variable_id' => '30'),
            array('id' => '325', 'question_id' => '295', 'variable_id' => '30'),
            array('id' => '326', 'question_id' => '296', 'variable_id' => '30'),
            array('id' => '327', 'question_id' => '297', 'variable_id' => '30'),
            array('id' => '328', 'question_id' => '298', 'variable_id' => '30'),
            array('id' => '329', 'question_id' => '299', 'variable_id' => '30'),
            array('id' => '330', 'question_id' => '300', 'variable_id' => '30'),
            array('id' => '331', 'question_id' => '301', 'variable_id' => '30'),
            array('id' => '332', 'question_id' => '302', 'variable_id' => '30'),
            array('id' => '333', 'question_id' => '303', 'variable_id' => '30'),
            array('id' => '334', 'question_id' => '304', 'variable_id' => '30'),
            array('id' => '335', 'question_id' => '305', 'variable_id' => '30'),
            array('id' => '336', 'question_id' => '306', 'variable_id' => '30'),
            array('id' => '337', 'question_id' => '263', 'variable_id' => '31'),
            array('id' => '338', 'question_id' => '264', 'variable_id' => '31'),
            array('id' => '339', 'question_id' => '266', 'variable_id' => '31'),
            array('id' => '340', 'question_id' => '267', 'variable_id' => '31'),
            array('id' => '341', 'question_id' => '269', 'variable_id' => '31'),
            array('id' => '342', 'question_id' => '270', 'variable_id' => '31'),
            array('id' => '343', 'question_id' => '271', 'variable_id' => '31'),
            array('id' => '344', 'question_id' => '272', 'variable_id' => '31'),
            array('id' => '345', 'question_id' => '274', 'variable_id' => '31'),
            array('id' => '346', 'question_id' => '276', 'variable_id' => '31'),
            array('id' => '347', 'question_id' => '283', 'variable_id' => '31'),
            array('id' => '348', 'question_id' => '284', 'variable_id' => '31'),
            array('id' => '349', 'question_id' => '285', 'variable_id' => '31'),
            array('id' => '350', 'question_id' => '286', 'variable_id' => '31'),
            array('id' => '351', 'question_id' => '288', 'variable_id' => '31'),
            array('id' => '352', 'question_id' => '290', 'variable_id' => '31'),
            array('id' => '353', 'question_id' => '292', 'variable_id' => '31'),
            array('id' => '354', 'question_id' => '294', 'variable_id' => '31'),
            array('id' => '355', 'question_id' => '295', 'variable_id' => '31'),
            array('id' => '356', 'question_id' => '296', 'variable_id' => '31'),
            array('id' => '357', 'question_id' => '297', 'variable_id' => '31'),
            array('id' => '358', 'question_id' => '301', 'variable_id' => '31'),
            array('id' => '359', 'question_id' => '302', 'variable_id' => '31'),
            array('id' => '360', 'question_id' => '303', 'variable_id' => '31'),
            array('id' => '361', 'question_id' => '306', 'variable_id' => '31'),
            array('id' => '362', 'question_id' => '268', 'variable_id' => '32'),
            array('id' => '363', 'question_id' => '277', 'variable_id' => '32'),
            array('id' => '364', 'question_id' => '278', 'variable_id' => '32'),
            array('id' => '365', 'question_id' => '279', 'variable_id' => '32'),
            array('id' => '366', 'question_id' => '280', 'variable_id' => '32'),
            array('id' => '367', 'question_id' => '281', 'variable_id' => '32'),
            array('id' => '368', 'question_id' => '287', 'variable_id' => '32'),
            array('id' => '369', 'question_id' => '291', 'variable_id' => '32'),
            array('id' => '370', 'question_id' => '298', 'variable_id' => '32'),
            array('id' => '371', 'question_id' => '304', 'variable_id' => '32'),
            array('id' => '372', 'question_id' => '265', 'variable_id' => '33'),
            array('id' => '373', 'question_id' => '273', 'variable_id' => '33'),
            array('id' => '374', 'question_id' => '275', 'variable_id' => '33'),
            array('id' => '375', 'question_id' => '282', 'variable_id' => '33'),
            array('id' => '376', 'question_id' => '289', 'variable_id' => '33'),
            array('id' => '377', 'question_id' => '293', 'variable_id' => '33'),
            array('id' => '378', 'question_id' => '299', 'variable_id' => '33'),
            array('id' => '379', 'question_id' => '300', 'variable_id' => '33'),
            array('id' => '380', 'question_id' => '305', 'variable_id' => '33'),
            array('id' => '381', 'question_id' => '307', 'variable_id' => '34'),
            array('id' => '382', 'question_id' => '308', 'variable_id' => '34'),
            array('id' => '383', 'question_id' => '309', 'variable_id' => '34'),
            array('id' => '384', 'question_id' => '310', 'variable_id' => '34'),
            array('id' => '385', 'question_id' => '311', 'variable_id' => '34'),
            array('id' => '386', 'question_id' => '312', 'variable_id' => '34'),
            array('id' => '387', 'question_id' => '313', 'variable_id' => '34'),
            array('id' => '388', 'question_id' => '314', 'variable_id' => '34'),
            array('id' => '389', 'question_id' => '315', 'variable_id' => '34'),
            array('id' => '390', 'question_id' => '316', 'variable_id' => '34'),
            array('id' => '391', 'question_id' => '317', 'variable_id' => '34'),
            array('id' => '392', 'question_id' => '318', 'variable_id' => '34'),
            array('id' => '393', 'question_id' => '319', 'variable_id' => '34'),
            array('id' => '394', 'question_id' => '320', 'variable_id' => '34'),
            array('id' => '395', 'question_id' => '321', 'variable_id' => '34'),
            array('id' => '396', 'question_id' => '322', 'variable_id' => '34'),
            array('id' => '397', 'question_id' => '323', 'variable_id' => '34'),
            array('id' => '398', 'question_id' => '324', 'variable_id' => '34'),
            array('id' => '399', 'question_id' => '325', 'variable_id' => '34'),
            array('id' => '400', 'question_id' => '326', 'variable_id' => '34'),
            array('id' => '401', 'question_id' => '327', 'variable_id' => '34'),
            array('id' => '402', 'question_id' => '328', 'variable_id' => '34'),
            array('id' => '403', 'question_id' => '329', 'variable_id' => '34'),
            array('id' => '404', 'question_id' => '330', 'variable_id' => '34'),
            array('id' => '405', 'question_id' => '331', 'variable_id' => '34'),
            array('id' => '406', 'question_id' => '332', 'variable_id' => '34'),
            array('id' => '407', 'question_id' => '333', 'variable_id' => '34'),
            array('id' => '408', 'question_id' => '334', 'variable_id' => '34'),
            array('id' => '409', 'question_id' => '335', 'variable_id' => '34'),
            array('id' => '410', 'question_id' => '336', 'variable_id' => '34'),
            array('id' => '411', 'question_id' => '337', 'variable_id' => '34'),
            array('id' => '412', 'question_id' => '338', 'variable_id' => '34'),
            array('id' => '413', 'question_id' => '339', 'variable_id' => '34'),
            array('id' => '414', 'question_id' => '340', 'variable_id' => '34'),
            array('id' => '415', 'question_id' => '341', 'variable_id' => '34'),
            array('id' => '416', 'question_id' => '342', 'variable_id' => '34'),
            array('id' => '417', 'question_id' => '343', 'variable_id' => '34'),
            array('id' => '418', 'question_id' => '344', 'variable_id' => '34'),
            array('id' => '419', 'question_id' => '345', 'variable_id' => '34'),
            array('id' => '420', 'question_id' => '346', 'variable_id' => '35'),
            array('id' => '421', 'question_id' => '347', 'variable_id' => '35'),
            array('id' => '422', 'question_id' => '348', 'variable_id' => '35'),
            array('id' => '423', 'question_id' => '349', 'variable_id' => '35'),
            array('id' => '424', 'question_id' => '350', 'variable_id' => '35'),
            array('id' => '425', 'question_id' => '351', 'variable_id' => '35'),
            array('id' => '426', 'question_id' => '352', 'variable_id' => '35'),
            array('id' => '427', 'question_id' => '353', 'variable_id' => '35'),
            array('id' => '428', 'question_id' => '354', 'variable_id' => '35'),
            array('id' => '429', 'question_id' => '355', 'variable_id' => '35'),
            array('id' => '430', 'question_id' => '356', 'variable_id' => '35'),
            array('id' => '431', 'question_id' => '357', 'variable_id' => '35'),
            array('id' => '432', 'question_id' => '358', 'variable_id' => '35'),
            array('id' => '433', 'question_id' => '359', 'variable_id' => '35'),
            array('id' => '434', 'question_id' => '360', 'variable_id' => '35'),
            array('id' => '435', 'question_id' => '361', 'variable_id' => '35'),
            array('id' => '436', 'question_id' => '362', 'variable_id' => '36'),
            array('id' => '437', 'question_id' => '363', 'variable_id' => '36'),
            array('id' => '438', 'question_id' => '364', 'variable_id' => '36'),
            array('id' => '439', 'question_id' => '365', 'variable_id' => '36'),
            array('id' => '440', 'question_id' => '366', 'variable_id' => '36'),
            array('id' => '441', 'question_id' => '367', 'variable_id' => '36'),
            array('id' => '442', 'question_id' => '368', 'variable_id' => '36'),
            array('id' => '443', 'question_id' => '369', 'variable_id' => '36'),
            array('id' => '444', 'question_id' => '370', 'variable_id' => '36'),
            array('id' => '445', 'question_id' => '371', 'variable_id' => '36'),
            array('id' => '446', 'question_id' => '372', 'variable_id' => '37'),
            array('id' => '447', 'question_id' => '373', 'variable_id' => '37'),
            array('id' => '448', 'question_id' => '374', 'variable_id' => '37'),
            array('id' => '449', 'question_id' => '375', 'variable_id' => '37'),
            array('id' => '450', 'question_id' => '376', 'variable_id' => '37'),
            array('id' => '451', 'question_id' => '377', 'variable_id' => '37'),
            array('id' => '452', 'question_id' => '378', 'variable_id' => '37'),
            array('id' => '453', 'question_id' => '379', 'variable_id' => '37'),
            array('id' => '454', 'question_id' => '380', 'variable_id' => '37'),
            array('id' => '455', 'question_id' => '381', 'variable_id' => '37'),
            array('id' => '456', 'question_id' => '382', 'variable_id' => '37'),
            array('id' => '457', 'question_id' => '383', 'variable_id' => '37'),
            array('id' => '458', 'question_id' => '384', 'variable_id' => '37'),
            array('id' => '459', 'question_id' => '385', 'variable_id' => '37'),
            array('id' => '460', 'question_id' => '386', 'variable_id' => '37'),
            array('id' => '461', 'question_id' => '387', 'variable_id' => '37'),
            array('id' => '462', 'question_id' => '388', 'variable_id' => '37'),
            array('id' => '463', 'question_id' => '389', 'variable_id' => '37'),
            array('id' => '464', 'question_id' => '390', 'variable_id' => '37'),
            array('id' => '465', 'question_id' => '391', 'variable_id' => '37'),
            array('id' => '466', 'question_id' => '392', 'variable_id' => '37'),
            array('id' => '467', 'question_id' => '393', 'variable_id' => '37'),
            array('id' => '468', 'question_id' => '394', 'variable_id' => '37'),
            array('id' => '469', 'question_id' => '395', 'variable_id' => '37'),
            array('id' => '470', 'question_id' => '396', 'variable_id' => '37'),
            array('id' => '471', 'question_id' => '397', 'variable_id' => '37'),
            array('id' => '472', 'question_id' => '398', 'variable_id' => '38'),
            array('id' => '473', 'question_id' => '399', 'variable_id' => '38'),
            array('id' => '474', 'question_id' => '400', 'variable_id' => '38'),
            array('id' => '475', 'question_id' => '401', 'variable_id' => '38'),
            array('id' => '476', 'question_id' => '402', 'variable_id' => '38'),
            array('id' => '477', 'question_id' => '403', 'variable_id' => '38'),
            array('id' => '478', 'question_id' => '404', 'variable_id' => '38'),
            array('id' => '479', 'question_id' => '405', 'variable_id' => '38'),
            array('id' => '480', 'question_id' => '406', 'variable_id' => '38'),
            array('id' => '481', 'question_id' => '407', 'variable_id' => '38'),
            array('id' => '482', 'question_id' => '408', 'variable_id' => '38'),
            array('id' => '483', 'question_id' => '409', 'variable_id' => '38'),
            array('id' => '484', 'question_id' => '410', 'variable_id' => '38'),
            array('id' => '485', 'question_id' => '411', 'variable_id' => '38'),
            array('id' => '486', 'question_id' => '412', 'variable_id' => '38'),
            array('id' => '487', 'question_id' => '413', 'variable_id' => '38'),
            array('id' => '488', 'question_id' => '414', 'variable_id' => '38'),
            array('id' => '489', 'question_id' => '415', 'variable_id' => '38'),
            array('id' => '490', 'question_id' => '416', 'variable_id' => '38'),
            array('id' => '491', 'question_id' => '417', 'variable_id' => '38'),
            array('id' => '492', 'question_id' => '418', 'variable_id' => '38'),
            array('id' => '493', 'question_id' => '419', 'variable_id' => '38'),
            array('id' => '494', 'question_id' => '420', 'variable_id' => '39'),
            array('id' => '495', 'question_id' => '421', 'variable_id' => '39'),
            array('id' => '496', 'question_id' => '422', 'variable_id' => '39'),
            array('id' => '497', 'question_id' => '423', 'variable_id' => '39'),
            array('id' => '498', 'question_id' => '424', 'variable_id' => '39'),
            array('id' => '499', 'question_id' => '425', 'variable_id' => '39'),
            array('id' => '500', 'question_id' => '426', 'variable_id' => '39'),
            array('id' => '501', 'question_id' => '427', 'variable_id' => '39'),
            array('id' => '502', 'question_id' => '428', 'variable_id' => '39'),
            array('id' => '503', 'question_id' => '429', 'variable_id' => '39'),
            array('id' => '504', 'question_id' => '430', 'variable_id' => '39'),
            array('id' => '505', 'question_id' => '431', 'variable_id' => '39'),
            array('id' => '506', 'question_id' => '432', 'variable_id' => '39'),
            array('id' => '507', 'question_id' => '433', 'variable_id' => '39'),
            array('id' => '508', 'question_id' => '434', 'variable_id' => '39'),
            array('id' => '509', 'question_id' => '435', 'variable_id' => '39'),
            array('id' => '510', 'question_id' => '436', 'variable_id' => '39'),
            array('id' => '511', 'question_id' => '437', 'variable_id' => '39'),
            array('id' => '512', 'question_id' => '438', 'variable_id' => '39'),
            array('id' => '513', 'question_id' => '439', 'variable_id' => '39'),
            array('id' => '514', 'question_id' => '440', 'variable_id' => '39'),
            array('id' => '515', 'question_id' => '580', 'variable_id' => '40'),
            array('id' => '516', 'question_id' => '581', 'variable_id' => '40'),
            array('id' => '517', 'question_id' => '582', 'variable_id' => '40'),
            array('id' => '518', 'question_id' => '583', 'variable_id' => '40'),
            array('id' => '519', 'question_id' => '584', 'variable_id' => '40'),
            array('id' => '520', 'question_id' => '585', 'variable_id' => '40'),
            array('id' => '521', 'question_id' => '586', 'variable_id' => '40'),
            array('id' => '522', 'question_id' => '587', 'variable_id' => '40'),
            array('id' => '523', 'question_id' => '588', 'variable_id' => '40'),
            array('id' => '524', 'question_id' => '589', 'variable_id' => '40'),
            array('id' => '525', 'question_id' => '590', 'variable_id' => '40'),
            array('id' => '526', 'question_id' => '591', 'variable_id' => '40'),
            array('id' => '527', 'question_id' => '592', 'variable_id' => '40'),
            array('id' => '528', 'question_id' => '593', 'variable_id' => '40'),
            array('id' => '529', 'question_id' => '594', 'variable_id' => '40'),
            array('id' => '530', 'question_id' => '595', 'variable_id' => '40'),
            array('id' => '531', 'question_id' => '596', 'variable_id' => '40'),
            array('id' => '532', 'question_id' => '597', 'variable_id' => '40'),
            array('id' => '533', 'question_id' => '598', 'variable_id' => '40'),
            array('id' => '534', 'question_id' => '599', 'variable_id' => '40'),
            array('id' => '535', 'question_id' => '600', 'variable_id' => '40')
        );

        foreach ($variables as $variable) {
            DB::table('variables')->insert($variable);
        }

        foreach ($question_variable as $relation) {
            DB::table('question_variable')->insert($relation);
        }
    }
}
